# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LWShareView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LWShareView
  pod 'Masonry','1.0.1'
  pod 'ReactiveCocoa', '~> 2.4.7'

  target 'LWShareViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LWShareViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
